name: API Test Execution

on:
   
    workflow_dispatch: 
        inputs:
            Platform:
                description: 'Enter Platform type'
                type: string
                required: true
                default: web
           
jobs:
    SettingupEnv:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up java JDK 17'
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'zulu'
                  cache: maven
            - run: mvn --version
            - name: build with maven
              run: |
                cd UNIFIED_AUTOMATION
                mvn clean
            - name: Testcase execution
              run: |
                cd UNIFIED_AUTOMATION
                mvn clean test -Dmaven.test.failure.ignore=true -fae
  
