name: API Test Execution

on:
   
    workflow_dispatch: 
        inputs:
            Platform:
                description: 'Enter Platform type'
                type: string
                required: true
                default: web
           
jobs:
    SettingupEnv:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up java JDK 17'
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'zulu'
                  cache: maven
            - run: mvn --version
            - name: build with maven
              run: |
                cd Unified_Utility
                mvn clean
            - name: Testcase execution
              run: |
                cd Unified_Utility
                mvn clean test -Dmaven.test.failure.ignore=true -fae
            - name: upload Report
            - uses: actions/upload-artifact@v3.1.2
              with:
                name: test-report
                path: "/home/runner/work/Unified_Automation/Unified_Automation/Unified_Utility/Extent/Teststst.html"
    
  
